# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BMI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(180, 185)
        Form.setFixedSize(180, 185)
        Form.setWindowIcon(QtGui.QIcon('бег.png'))
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(15, 32, 39, 255), stop:0.480226 rgba(32, 58, 67, 255), stop:1 rgba(44, 83, 100, 255));")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 40, 181, 91))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.data_layout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.data_layout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.data_layout_2.setContentsMargins(6, 0, 6, 6)
        self.data_layout_2.setSpacing(6)
        self.data_layout_2.setObjectName("data_layout_2")
        self.weight_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.weight_label_2.setStyleSheet("background-color:transparent;\n"
"color: rgb(255, 255, 255);")
        self.weight_label_2.setObjectName("weight_label_2")
        self.data_layout_2.addWidget(self.weight_label_2)
        self.weight_lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.weight_lineEdit_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 10px;                     /* <----  20px  */ \n"
"border: 2px solid #243b47 ;")
        self.weight_lineEdit_2.setObjectName("weight_lineEdit_2")
        self.data_layout_2.addWidget(self.weight_lineEdit_2)
        self.height_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.height_label_2.setEnabled(True)
        self.height_label_2.setStyleSheet("background-color:transparent;\n"
"color: rgb(255, 255, 255);")
        self.height_label_2.setObjectName("height_label_2")
        self.data_layout_2.addWidget(self.height_label_2)
        self.height_lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.height_lineEdit_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 10px;                     /* <----  20px  */ \n"
"border: 2px solid #243b47 ;\n"
"\n"
"")
        self.height_lineEdit_2.setObjectName("height_lineEdit_2")
        self.data_layout_2.addWidget(self.height_lineEdit_2)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 130, 181, 57))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.btns_layout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.btns_layout_2.setContentsMargins(20, 6, 20, 6)
        self.btns_layout_2.setObjectName("btns_layout_2")
        self.count_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.count_button_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(179, 158, 208);\n"
"background-color: rgb(20, 30, 48);\n"
"border-radius: 6px;                     /* <----  20px  */ \n"
"")
        self.count_button_2.setObjectName("count_button_2")
        self.btns_layout_2.addWidget(self.count_button_2)
        self.Result = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Result.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"\n"
"border-radius: 6px;                     /* <----  20px  */ \n"
"")
        self.Result.setObjectName("Result")
        self.btns_layout_2.addWidget(self.Result)
        self.BMI = QtWidgets.QLabel(Form)
        self.BMI.setGeometry(QtCore.QRect(0, 0, 181, 41))
        self.BMI.setStyleSheet("background-color:transparent;\n"
"color: rgb(255, 255, 255);")
        self.BMI.setObjectName("BMI")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ㅤ"))
        self.weight_label_2.setText(_translate("Form", "Введите свой вес(кг)"))
        self.height_label_2.setText(_translate("Form", "Введите свой рост(см)"))
        self.count_button_2.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.count_button_2.setText(_translate("Form", "Вычислить"))
        self.Result.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.BMI.setToolTip(_translate("Form", "<font color=\"black\">Вычисление ИНДЕКСА МАССЫ ТЕЛА</font>"))
        self.BMI.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Вычисление BMI</span></p></body></html>"))
        self.count_button_2.clicked.connect(self.countResult_clicked)



    def countResult_clicked(self):
        m = int(self.weight_lineEdit_2.text())
        h = int(self.height_lineEdit_2.text())
        hm = h / 100
        h2 = hm ** 2
        i = m / h2
        if i == 16 or i < 16:
            self.Result.setText("<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Не норма</span></p></body></html>")
            self.Result.setToolTip("<font color=\"white\">Выраженный дефицит массы тела</font>")
#print(f'Ваш ИМТ равен {i} (Выраженный дефицит массы тела)')

        elif i >= 16 and i <= 18:
            self.Result.setText("<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Не норма</span></p></body></html>")
            self.Result.setToolTip("<font color=\"white\">Недостаточная масса тела</font>")
#print(f'Ваш ИМТ равен {i} (Недостаточная масса тела)')
        elif i > 18 and i <= 25:
            self.Result.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">НОРМА</span></p></body></html>")
            self.Result.setToolTip("<font color=\"white\">Всё хорошо!</font>")
#print(f'Ваш ИМТ равен {i} (НОРМА)')
        elif i > 25 and i <= 30:
            self.Result.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Не норма</span></p></body></html>")
            self.Result.setToolTip("<font color=\"white\">Избыточная масса тела</font>")
#print(f'Ваш ИМТ равен {i} (Избыточная масса тела)')
        elif i > 30 and i <= 35:
            self.Result.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Не норма</span></p></body></html>")
            self.Result.setToolTip("<font color=\"white\">Ожирение первой степени</font>")
#print(f'Ваш ИМТ равен {i} (Ожирение первой степени)')
        elif i > 35 and i <= 40:
            self.Result.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Не норма</span></p></body></html>")
            self.Result.setToolTip("<font color=\"white\">Ожирение второй степени</font>")
#print(f'Ваш ИМТ равен {i} (Ожирение второй степени)')
        elif i > 40:
            self.Result.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Не норма</span></p></body></html>")
            self.Result.setToolTip("<font color=\"white\">Ожирение третьей степени</font>")
#print(f'Ваш ИМТ равен {i} (Ожирение третьей степени)')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
